name: PHP

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['8.1', '8.2', '8.3', '8.4']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    name: PHP ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: intl, pdo_pgsql, zip
          coverage: xdebug
          ini-values: xdebug.mode=coverage

      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update
          sudo apt install google-chrome-stable
      - run: npm install

      - run: composer validate --strict

      #- name: Cache Composer packages
      #  id: composer-cache
      #  uses: actions/cache@v4
      #  with:
      #    path: vendor
      #    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - run: composer install --prefer-dist --no-progress
      - run: composer run-script dev:lint:php
      - run: composer run-script dev:lint:phpcs
      - run: composer run-script dev:analyze:phpstan-${{ matrix.version }}
      - run: npx selenium-standalone install && npx selenium-standalone start &
      - run: |
          while ! curl -sSL http://127.0.0.1:4444/wd/hub/status
          do
            echo "Waiting for Selenium to start..."
            sleep 5
          done

      - run: composer run-script dev:test:unit
        env:
          PHPPGADMIN_TEST_SERVER_PASSWORD: ${{ vars.PHPPGADMIN_TEST_SERVER_PASSWORD }}

      - run: composer run-script dev:test:coverage:ci
        env:
          BROWSER: chrome
          PHPPGADMIN_TEST_SERVER_PASSWORD: ${{ vars.PHPPGADMIN_TEST_SERVER_PASSWORD }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ matrix.version == '8.1' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ringostarr80/phpPgAdmin

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-output-${{ matrix.version }}
          path: tests/_output