name: PHP

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
        pg-version: [ '17' ]

    services:
      postgres:
        image: postgres:${{ matrix.pg-version }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    name: PHP ${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, pdo_pgsql, xdebug, zip
          coverage: xdebug
          ini-values: xdebug.mode=coverage,error_reporting=E_ALL,display_errors=On

      - run: composer validate --strict
      - run: composer install --prefer-dist --no-progress
      - run: composer run-script dev:lint:php
      - run: composer run-script dev:lint:phpcs
      - run: composer run-script dev:analyze:phpstan-${{ matrix.php-version }}
      - run: composer run-script dev:test:unit
        env:
          PHPPGADMIN_TEST_SERVER_HOSTNAME: localhost
          PHPPGADMIN_TEST_SERVER_PASSWORD: ${{ vars.PHPPGADMIN_TEST_SERVER_PASSWORD }}