name: Generate and Upload SBOM

permissions:
  contents: read # only needs to read the repository contents

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Generate SBOM
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: 8.5
        extensions: intl, pdo_pgsql, xdebug, zip

    - name: Restore dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate SBOMs
      run: composer CycloneDX:make-sbom --output-file=phppgadmin-sbom.xml --output-reproducible --validate --spec-version=1.6
    
    - name: Upload SBOM for phpPgAdmin to DependencyTrack
      env:
        DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
        DTRACK_URL: ${{ secrets.DTRACK_URL }}
      run: |
        curl -X "POST" \
            "${DTRACK_URL}/api/v1/bom" \
            -H "X-API-Key: ${DTRACK_API_KEY}" \
            -H "Content-Type: multipart/form-data" \
            -F "projectName=phpPgAdmin" \
            -F "bom=@phppgadmin-sbom.xml"
